<?php

namespace App\Jobs;

use App\Facades\Store;
use App\Models\PhotoStudioGeneration;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use RuntimeException;
use Throwable;

class PushImageToStore implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public int $tries = 3;

    /**
     * Backoff intervals (seconds) between retries.
     *
     * @var array<int, int>
     */
    public array $backoff = [30, 120, 300];

    public function __construct(
        public int $generationId,
    ) {
        $this->onQueue('ai');
    }

    public function handle(): void
    {
        $generation = PhotoStudioGeneration::with(['product.feed.storeConnection'])
            ->find($this->generationId);

        if (! $generation) {
            Log::warning('PushImageToStore: Generation not found', [
                'generation_id' => $this->generationId,
            ]);

            return;
        }

        $connection = $generation->getStoreConnection();

        if (! $connection) {
            throw new RuntimeException('No store connection found for this product.');
        }

        if (! $connection->isConnected()) {
            throw new RuntimeException('Store connection is not active.');
        }

        $product = $generation->product;
        $externalId = $product->external_id ?? null;

        if (! $externalId) {
            throw new RuntimeException('Product has no external store ID.');
        }

        if (! $generation->storage_path || ! $generation->storage_disk) {
            throw new RuntimeException('Generation has no stored image.');
        }

        $imageUrl = $this->resolveImageUrl($generation);

        if (! $imageUrl) {
            throw new RuntimeException('Could not resolve public URL for the image.');
        }

        try {
            $adapter = Store::forPlatform($connection->platform);

            $mediaId = $adapter->addProductImage(
                connection: $connection,
                productId: $externalId,
                imageUrl: $imageUrl,
                alt: $this->buildAltText($generation),
            );

            $generation->markAsPushedToStore();

            Log::info('PushImageToStore: Successfully pushed image to store', [
                'generation_id' => $generation->id,
                'product_id' => $product->id,
                'external_id' => $externalId,
                'media_id' => $mediaId,
            ]);
        } catch (Throwable $e) {
            Log::error('PushImageToStore: Failed to push image to store', [
                'generation_id' => $generation->id,
                'product_id' => $product->id,
                'external_id' => $externalId,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    public function failed(Throwable $exception): void
    {
        Log::error('PushImageToStore: Job permanently failed', [
            'generation_id' => $this->generationId,
            'error' => $exception->getMessage(),
        ]);
    }

    /**
     * Resolve the public URL for the stored image.
     */
    protected function resolveImageUrl(PhotoStudioGeneration $generation): ?string
    {
        try {
            return Storage::disk($generation->storage_disk)->url($generation->storage_path);
        } catch (Throwable) {
            return null;
        }
    }

    /**
     * Build alt text for the image from product and generation data.
     */
    protected function buildAltText(PhotoStudioGeneration $generation): string
    {
        $product = $generation->product;

        $parts = array_filter([
            $product?->title,
            $generation->model ? "AI generated by {$generation->model}" : 'AI generated image',
        ]);

        return implode(' - ', $parts);
    }
}
